name: Node.js CI

on:
  push:
    branches: [ "guest-login" ]
  pull_request:
    branches: [ "guest-login" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./Back-End-Node

    - name: Build project
      run: npm run build --if-present
      working-directory: ./Back-End-Node

    - name: Run tests
      run: npm test
      working-directory: ./Back-End-Node

  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./front-end

    - name: Build project
      run: npm run build --if-present
      working-directory: ./front-end

    - name: Run tests
      run: npm test
      working-directory: ./front-end
